european_capitals = [
    "Tirana",
    "Andorra la Vella",
    "Yerevan",
    "Vienna",
    "Baku",
    "Minsk",
    "Brussels",
    "Sarajevo",
    "Sofia",
    "Zagreb",
    "Nicosia",
    "Prague",
    "Copenhagen",
    "Tallinn",
    "Helsinki",
    "Paris",
    "Tbilisi",
    "Berlin",
    "Athens",
    "Budapest",
    "Reykjavik",
    "Dublin",
    "Rome",
    "Nur-Sultan (Astana)",
    "Pristina",
    "Riga",
    "Vaduz",
    "Vilnius",
    "Luxembourg",
    "Valletta",
    "Chisinau",
    "Monaco",
    "Podgorica",
    "Amsterdam",
    "Skopje",
    "Oslo",
    "Warsaw",
    "Lisbon",
    "Bucharest",
    "Moscow",
    "San Marino",
    "Belgrade",
    "Bratislava",
    "Ljubljana",
    "Madrid",
    "Stockholm",
    "Bern",
    "Ankara",
    "Kyiv",
    "London",
    "Vatican City"
]
